<?php

/**
 * @file
 * Contains hooks and functions for commerce_quote_cart.
 */

use Drupal\commerce\Context;
use Drupal\commerce\PurchasableEntityInterface;
use Drupal\commerce_quote_cart\QuoteCartHelper;
use Drupal\commerce_product\Entity\ProductInterface;
use Drupal\commerce_product\Entity\ProductVariationInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Markup;

/**
 * Get the current variation.
 *
 * @param array $storage
 *
 * @return \Drupal\commerce_product\Entity\ProductVariationInterface|\Drupal\Core\Entity\EntityInterface|null
 *
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function commerce_quote_cart_get_current_variation(array $storage) {
  if (isset($storage['selected_variation'])) {
    $variationId = $storage['selected_variation'];

    /** @var \Drupal\Core\Entity\ContentEntityInterface $variation */
    return Drupal::entityTypeManager()->getStorage('commerce_product_variation')->load($variationId);
  }

  /** @var ProductInterface $product */
  $product = $storage['product'];

  return $product->getDefaultVariation();
}

/**
 * Get the store.
 *
 * @param \Drupal\commerce\PurchasableEntityInterface $entity
 *   The entity being purchased.
 *
 * @return \Drupal\commerce_store\Entity\StoreInterface|mixed
 *
 * @throws Exception
 */
function commerce_quote_cart_get_store(PurchasableEntityInterface $entity) {
  $stores = $entity->getStores();

  if (count($stores) === 1) {
    $store = reset($stores);
  }
  else {
    $store = Drupal::service('commerce_store.store_context')->getStore();
    if (!in_array($store, $stores, FALSE)) {
      // Indicates that the site listings are not filtered properly.
      throw new Exception("The given entity can't be purchased from the current store.");
    }
  }

  return $store;
}

/**
 * Convert on submit.
 *
 * @param array $form
 *   The form array.
 * @param FormStateInterface $form_state
 *   The form state interface object.
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function commerce_quote_cart_submit_convert(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $form_state->getBuildInfo()['args'][0];

  foreach ($view->result as $resultRow) {
    if (!isset($resultRow->_entity)) {
      continue;
    }

    /** @var \Drupal\commerce_order\Entity\OrderInterface $order */
    $order = $resultRow->_entity;

    QuoteCartHelper::convertToQuote($order);
  }
}

/**
 * Submit quote.
 *
 * @param array $form
 *   The form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state object.
 *
 * @return void
 */
function commerce_quote_cart_submit_quote(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\commerce_cart\Form\AddToCartForm $addToCartForm */
  $addToCartForm = $form_state->getBuildInfo()['callback_object'];

  /** @var \Drupal\commerce_order\Entity\OrderItemInterface $order_item */
  $order_item = $addToCartForm->getEntity();
  $order_item->set('field_quote', ['value' => '1']);

  $addToCartForm->submitForm($form, $form_state);
}

/**
 * Implements hook_preprocess_block().
 */
function commerce_quote_cart_preprocess_block(&$variables) {
  if (in_array($variables['elements']['#id'], ['product_variations', 'product_variations_mobile'])) {
      $config = Drupal::config('block.block.' . $variables['elements']['#id']);
      if ($config->get('label_display') == 'visible') {
          $variables['label'] = commerce_quote_cart_block_label($variables);
      }
      else {
          $variables['label'] = '';
      }
  }

  if ($variables['plugin_id'] === 'page_title_block' && Drupal::routeMatch()->getRouteName() === 'entity.commerce_order.user_view') {
    /** @var \Drupal\commerce_order\Entity\OrderInterface $order */
    $order = Drupal::routeMatch()->getParameter('commerce_order');

    if ($order) {
      $title = QuoteCartHelper::isPurchaseCart($order) ? 'Order' : 'Quote';
      $variables['content']['#title'] = t('@title number: @order_number', [
        '@title' => $title,
        '@order_number' => $order->getOrderNumber(),
      ]);
    }
  }
}

/**
 * Implements hook_preprocess_commerce_order().
 */
function commerce_quote_cart_preprocess_commerce_order(&$variables) {
  commerce_quote_cart_populate_order_variables($variables);
}

/**
 * Implements hook_preprocess_commerce_order_receipt().
 */
function commerce_quote_cart_preprocess_commerce_order_receipt(&$variables) {
  commerce_quote_cart_populate_order_variables($variables);
}

/**
 * Implements hook_preprocess_commerce_checkout_completion_message().
 */
function commerce_quote_cart_preprocess_commerce_checkout_completion_message(&$variables) {
  commerce_quote_cart_populate_order_variables($variables);
}

/**
 * @param array $variables
 *
 * @return void
 */
function commerce_quote_cart_populate_order_variables(array &$variables): void {
  if (isset($variables['order_entity'])) {
    /** @var Drupal\commerce_order\Entity\OrderInterface $order */
    $order = $variables['order_entity'];

    $variables['order_label'] = QuoteCartHelper::isPurchaseCart($order) ? t('Order') : t('Quote');
    $variables['is_quote'] = !QuoteCartHelper::isPurchaseCart($order);

    if (isset($variables['order']['order_number']) && $variables['is_quote']) {
      $variables['order']['order_number']['#title'] = t('Quote number');
    }
  }
}

function commerce_quote_cart_block_label($variables) {
  $label = $variables['label'];

  /** @var \Drupal\commerce_product\Entity\ProductInterface $product */
  $product = $variables['content']['content']['#commerce_product'];

  if ($product instanceof ProductInterface) {
    $purchasable = commerce_quote_cart_product_is_purchasable($product);
    $in_stock = commerce_quote_cart_get_product_stock_level($product) > 0;
    if ($purchasable && $in_stock) {
      $label = 'Add to Cart';
    }
  }

  return $label;
}

/**
 * Loops through a given product's variations and returns their total stock.
 *
 * @param \Drupal\commerce_product\Entity\ProductInterface $product
 *   The product.
 *
 * @return int
 *   Total of product's variations' stock levels
 */
function commerce_quote_cart_get_product_stock_level(ProductInterface $product): int {
  $variations = $product->getVariations();
  $stock = 0;

  foreach ($variations as $variation) {
    $stock += commerce_quote_cart_get_variation_stock_level($variation);
  }
  return $stock;
}

/**
 * Returns the current stock level of a given product variation.
 *
 * @param \Drupal\commerce_product\Entity\ProductVariationInterface $variation
 *   The variation.
 *
 * @return int
 *   The stock level of the variation.
 *
 * @throws \Exception
 */
function commerce_quote_cart_get_variation_stock_level(ProductVariationInterface $variation): int {
  /** @var \Drupal\commerce_stock\StockServiceManagerInterface $stockManager */
  $stockManager = Drupal::service('commerce_stock.service_manager');

  return $stockManager->getStockLevel($variation);
}

/**
 * Returns a boolean stating whether a variation is in stock.
 *
 * @param Drupal\commerce_product\Entity\ProductVariationInterface $variation
 *   The variation.
 *
 * @return bool
 *   Whether the variation is in stock.
 */
function commerce_quote_cart_variation_in_stock(ProductVariationInterface $variation): bool {
  return commerce_quote_cart_get_variation_stock_level($variation) > 0;
}

/**
 * Returns a boolean stating whether or not the given variation is purchasable.
 *
 * @param \Drupal\commerce_product\Entity\ProductVariationInterface $variation
 *   The product variation entity.
 *
 * @return bool
 *   Whether the variation is purchasable.
 */
function commerce_quote_cart_variation_is_purchasable(ProductVariationInterface $variation): bool {
  $purchasableField = 'field_available_for_purchase';

  return ($variation->hasField($purchasableField) && $variation->get($purchasableField)->value);
}

/**
 * Whether a product has at least one purchasable variation.
 *
 * @param \Drupal\commerce_product\Entity\ProductInterface $product
 *   The product entity.
 *
 * @return bool
 *   Whether or not the product has purchasable variations.
 */
function commerce_quote_cart_product_is_purchasable(ProductInterface $product): bool {
  $variations = $product->getVariations();
  $purchasable = FALSE;

  foreach ($variations as $variation) {
    if (commerce_quote_cart_variation_is_purchasable($variation) && commerce_quote_cart_variation_in_stock($variation)) {
      $purchasable = TRUE;
      break;
    }
  }
  return $purchasable;
}

/**
 * Returns a boolean stating whether or not the given variation is quotable
 *
 * @param Drupal\commerce_product\Entity\ProductVariationInterface $variation
 *
 * @return bool Whether the variation is quotable
 */
function commerce_quote_cart_variation_is_quotable(ProductVariationInterface $variation) {
  $quotableField = 'field_available_for_quote';

  return ($variation->hasField($quotableField) && $variation->get($quotableField)->value);
}

/**
 * Implements hook_preprocess_field();
 */
function commerce_quote_cart_preprocess_field(&$variables) {
  if ($variables['element']['#field_name'] === 'price') {
    /** @var ProductVariationInterface $variation */
    $variation = $variables['element']['#object'];
    $view_mode = $variables['element']['#view_mode'];
    $purchasable = commerce_quote_cart_variation_is_purchasable($variation);
    $quotable = commerce_quote_cart_variation_is_quotable($variation);
    $current_user = Drupal::currentUser();
    $current_store = Drupal::service('commerce_store.current_store')->getStore();
    $context = new Context($current_user, $current_store);
    $stockLevel = commerce_quote_cart_stock_enforcement_get_stock_level($variation, $context);
    $already_ordered = commerce_quote_cart_stock_enforcement_get_ordered_quantity($variation, $context);
    $outOfStockMessage = '<div class="out-of-stock">' . t('<span>Temporarily out of stock</span><br>Request a quote and we\'ll contact you with more information') . '</div>';

    if (isset($variables['items'][0])) {

      $priceMarkup = NULL;

      if ($purchasable) {
        if ($stockLevel - $already_ordered <= 0) {
          if ($view_mode === 'variations') {
            $priceMarkup = $outOfStockMessage;
          }
          else {
            $priceMarkup = t('Quote');
          }
        }
      }
      else {
        if ($quotable) {
          $priceMarkup = t('Quote');
        }
        else {
          $priceMarkup = '';
        }
      }

      if (isset($priceMarkup)) {
        $variables['items'][0]['content'] = [
          '#markup' => $priceMarkup,
        ];
      }
    }
  }
}

/**
 * @param array $entities
 *   An array of entities.
 * @param string $entity_type
 *   The entity type.
 *
 * @throws \Drupal\Core\TypedData\Exception\MissingDataException
 */
function commerce_quote_cart_entity_storage_load(array $entities, string $entity_type) {
  if ($entity_type === 'commerce_order') {
    /** @var \Drupal\commerce_order\Entity\OrderInterface $order */
    foreach ($entities as $order) {
      $targetId = QuoteCartHelper::isPurchaseCart($order) ? 'default' : 'quote';
      $order->get('checkout_flow')->set(0, ['target_id' => $targetId]);
    }
  }
}

/**
 * Implements hook_commerce_shipping_methods_alter().
 */
function commerce_quote_cart_commerce_shipping_methods_alter(array &$shipping_methods, \Drupal\commerce_shipping\Entity\ShipmentInterface $shipment) {
  $shipping_methods = QuoteCartHelper::filterShippingMethods($shipping_methods, $shipment);
}

function commerce_quote_cart_set_triggering_element(array $form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $input = $form_state->getUserInput();

  foreach (['submit', 'quote'] as $button) {
    if (isset($input[$button])) {
      $form_state->setTriggeringElement($form['actions'][$button]);
      break;
    }
  }

  return $form;
}

/**
 * @param $variables
 *
 * @return void
 */
function commerce_quote_cart_preprocess_views_view_field(&$variables) {
  $supportedFields = [
    'total_price',
    'unit_price'
  ];

  /** @var Drupal\views\Plugin\views\field\EntityField $field */
  $field = $variables['field'];

  /** @var Drupal\views\ResultRow $row */
  $row = $variables['row'];
  $fieldName = array_key_exists('entity_field', $field->options) ? $field->options['entity_field'] : '';

  if ($fieldName && in_array($fieldName, $supportedFields, TRUE)) {
    $total = 0.00;
    $entity = $field->getEntity($row);

    if ($entity instanceof FieldableEntityInterface && $entity->hasField($fieldName) && !$entity->get($fieldName)->isEmpty()) {
      $total = (float) $entity->get($fieldName)->number;
    }

    if (!$total && $entity->hasField('field_quote') && $entity->get('field_quote')->value) {
      $variables['output'] = Markup::create('Quote');
    }
  }
}

/**
 * @param $variables
 *
 * @return void
 */
function commerce_quote_cart_preprocess_commerce_order_total_summary(&$variables) {
  /** @var \Drupal\commerce_price\Price $subtotal */
  $subtotal = $variables['totals']['subtotal'];

  /** @var \Drupal\commerce_price\Price $total */
  $total = $variables['totals']['total'];

  $variables['is_quote'] = ($subtotal->isZero() && $total->isZero());
}
